# sonar.projectKey=production-ready-notes-app-client
sonar.projectName=Production Ready Notes App - Client
sonar.projectVersion=1.0

# Path to source directory
sonar.sources=src
# Exclude test files from analysis
sonar.exclusions=src/**/*.test.tsx, src/**/*.spec.tsx, node_modules/**

# Path to test directory
sonar.tests=src
sonar.test.inclusions=src/**/*.test.tsx, src/**/*.spec.tsx

# Lcov report for coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Typscript support
sonar.typescript.tsconfigPath=tsconfig.json

# Dashboard Analysis
sonar.projectKey=frontend-project
sonar.host.url=http://localhost:9000
sonar.token=sqp_7fa2839f3426da17bbae034c0bc939c09845b337