import { useState } from "react";
import { useNoteContext } from "../contexts/note.context";
import type { INote } from "../types/note.types";
import JSZip from "jszip";
import {
  Archive,
  CheckCircle2,
  Circle,
  Download,
  FileText,
  Loader2,
} from "lucide-react";
import { Link } from "react-router-dom";

export default function ExportAllNotePage() {
  const { notes } = useNoteContext();
  const [selectedNoteIds, setSelectedNoteIds] = useState<Set<string>>(
    new Set(),
  );
  const [isExporting, setIsExporting] = useState(false);

  // Toggle single note
  const toggleNote = (id: string) => {
    const newSelected = new Set(selectedNoteIds);
    if (newSelected.has(id)) newSelected.delete(id);
    else newSelected.add(id);
    setSelectedNoteIds(newSelected);
  };

  // Toggle all visible notes
  const handleSelectAll = () => {
    if (selectedNoteIds.size === notes?.length) {
      setSelectedNoteIds(new Set());
    } else {
      setSelectedNoteIds(new Set(notes?.map((n) => n._id)));
    }
  };

  const generateHTML = (note: INote) => `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${note.title}</title>
        <style>
          body { font-family: sans-serif; line-height: 1.6; padding: 20px; }
          h1 { border-bottom: 2px solid #eee; }
        </style>
      </head>
      <body>
        <div class="container">
          <header>
            <h1>${note.title}</h1>
            <div class="meta">Last updated: ${new Date(note.updatedAt).toLocaleDateString()}</div>
          </header>
          <div class="content">Content: ${note.content}</div>
          <div class="footer">
            Generated by 10pShine Notes
          </div>
        </div>
      </body>
    </html>
  `;

  async function handleExport() {
    if (selectedNoteIds.size === 0) return;
    setIsExporting(true);

    try {
      const zip = new JSZip();
      const folder = zip.folder("My_Notes_Backup");
      const titleTracker: Record<string, number> = {};

      const notesToExport =
        notes?.filter((n) => selectedNoteIds.has(n._id)) || [];

      notesToExport.forEach((note) => {
        let safeTitle =
          note.title.replaceAll(/[<>:"/\\|?*]/g, "").replaceAll(/\s+/g, "_") ||
          "untitled";

        // Handle name collisions
        if (titleTracker[safeTitle] !== undefined) {
          titleTracker[safeTitle]++;
          safeTitle = `${safeTitle}_(${titleTracker[safeTitle]})`;
        } else {
          titleTracker[safeTitle] = 0;
        }

        folder?.file(`${safeTitle}.html`, generateHTML(note));
      });

      const content = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(content);
      const link = document.createElement("a");
      link.href = url;
      link.download = `10pShine_Notes_${new Date().toISOString().split("T")[0]}.zip`;
      document.body.appendChild(link);
      link.click();

      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    } finally {
      setIsExporting(false);
    }
  }

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      {/* Header section with glassmorphism */}
      <div className="sticky top-0 z-10 bg-white/80 backdrop-blur-md border-b border-gray-200 px-6 py-4">
        <div className="max-w-5xl mx-auto flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <nav className="flex items-center text-sm text-gray-500 mb-1">
              <Link
                to="/notes"
                className="hover:text-blue-600 transition-colors"
              >
                Notes
              </Link>
              <span className="mx-2">/</span>
              <span className="text-gray-900 font-medium">Export All</span>
            </nav>
            <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-2">
              <Archive className="w-6 h-6 text-blue-600" />
              Batch Export Notes
            </h1>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={handleSelectAll}
              className="px-4 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-100 rounded-xl transition-all"
            >
              {selectedNoteIds.size === notes?.length
                ? "Deselect All"
                : "Select All"}
            </button>
            <button
              onClick={handleExport}
              disabled={selectedNoteIds.size === 0 || isExporting}
              className={`flex items-center gap-2 px-6 py-2.5 rounded-xl font-bold shadow-lg transition-all ${
                selectedNoteIds.size === 0 || isExporting
                  ? "bg-gray-300 text-gray-500 cursor-not-allowed shadow-none"
                  : "bg-blue-600 text-white hover:bg-blue-700 hover:shadow-blue-200 active:scale-95"
              }`}
            >
              {isExporting ? (
                <Loader2 className="w-5 h-5 animate-spin" />
              ) : (
                <Download className="w-5 h-5" />
              )}
              {isExporting
                ? "Zipping..."
                : `Export ${selectedNoteIds.size} Notes`}
            </button>
          </div>
        </div>
      </div>

      {/* Note Selection List */}
      <main className="flex-1 max-w-5xl mx-auto w-full p-6">
        <div className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden">
          <div className="divide-y divide-gray-100 italic text-xs mb-2">
            {!notes?.length && (
              <div className="p-12 text-center text-gray-500">
                <FileText className="w-12 h-12 mx-auto mb-4 opacity-20" />
                <p>No notes found to export.</p>
              </div>
            )}
          </div>

          <div className="divide-y divide-gray-100">
            {notes?.map((note) => (
              <div
                key={note._id}
                onClick={() => toggleNote(note._id)}
                className={`flex items-center p-4 cursor-pointer transition-colors group ${
                  selectedNoteIds.has(note._id)
                    ? "bg-blue-50/50"
                    : "hover:bg-gray-50"
                }`}
              >
                <div className="mr-4">
                  {selectedNoteIds.has(note._id) ? (
                    <CheckCircle2 className="w-6 h-6 text-blue-600 fill-blue-50" />
                  ) : (
                    <Circle className="w-6 h-6 text-gray-300 group-hover:text-blue-400" />
                  )}
                </div>
                <div className="flex-1">
                  <h3 className="font-semibold text-gray-900 line-clamp-1">
                    {note.title}
                  </h3>
                  <p className="text-xs text-gray-500 mt-1">
                    Updated {new Date(note.updatedAt).toLocaleDateString()} •{" "}
                    {note.content.length} characters
                  </p>
                </div>
                <div className="text-xs font-mono text-gray-300">.html</div>
              </div>
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}
