import { ArrowUpFromLine } from "lucide-react";
import type { INote } from "../../types/note.types";

export default function ExportNoteButton({ note }: Readonly<{ note: INote }>) {
  const exportNoteAsHTML = (note: INote) => {
    const htmlContent = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${note.title}</title>
        <style>
          body { font-family: sans-serif; line-height: 1.6; padding: 20px; }
          h1 { border-bottom: 2px solid #eee; }
        </style>
      </head>
      <body>
        <div class="container">
          <header>
            <h1>${note.title}</h1>
            <div class="meta">Last updated: ${new Date(note.updatedAt).toLocaleDateString()}</div>
          </header>
          <div class="content">Content: ${note.content}</div>
          <div class="footer">
            Generated by 10pShine Notes
          </div>
        </div>
      </body>
    </html>
  `;

    const blob = new Blob([htmlContent], { type: "text/html" });
    const url = URL.createObjectURL(blob);

    // Robust filename sanitization
    const safeTitle = note.title
      .replaceAll(/[<>:"/\\|?*]/g, "") // Remove illegal characters
      .replaceAll(/\s+/g, "_")
      .substring(0, 100);

    const link = document.createElement("a");
    link.href = url;
    link.download = `${safeTitle || "untitled_note"}.html`;
    document.body.appendChild(link);
    link.click();

    // Cleanup
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <button
      onClick={(e) => {
        e.stopPropagation(); // Avoid triggering any card click events
        exportNoteAsHTML(note);
      }}
      className="p-1.5 text-gray-400 rounded-lg focus:outline-none cursor-pointer hover:bg-gray-100 hover:text-blue-600 transition-colors"
      title="Export as HTML"
      aria-label={`Export ${note.title} as HTML`}
    >
      <ArrowUpFromLine className="w-4 h-4" />
    </button>
  );
}
