import { render, screen, fireEvent } from "@testing-library/react";
import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import ExportNoteButton from "./ExportNoteButton";
import type { INote } from "../../types/note.types";

describe("ExportNoteButton Component", () => {
  const mockNote: INote = {
    _id: "test-export-123",
    title: "Project Alpha",
    content: "Planning for the <strong>next phase</strong>.",
    isPinned: false,
    user: "u123",
    createdAt: new Date().toISOString(),
    updatedAt: "2024-05-19T10:00:00.000Z",
  };

  beforeEach(() => {
    // Mock URL methods globally
    globalThis.URL.createObjectURL = vi
      .fn()
      .mockReturnValue("blob:mock-url-123");
    globalThis.URL.revokeObjectURL = vi.fn();

    // Mock anchor element interactions - use real element to satisfy JSDOM
    const mockAnchor = document.createElement("a");
    vi.spyOn(mockAnchor, "click").mockImplementation(() => {});

    const originalCreateElement = document.createElement.bind(document);
    vi.spyOn(document, "createElement").mockImplementation(
      (tagName: string) => {
        if (tagName === "a") return mockAnchor;
        return originalCreateElement(tagName);
      },
    );

    // Spy on body interactions without preventing them
    vi.spyOn(document.body, "appendChild");
    vi.spyOn(document.body, "removeChild");
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it("should export note with title, content, and footer when clicked", () => {
    // Spy on Blob to inspect its content
    const BlobSpy = vi.spyOn(globalThis, "Blob");

    render(<ExportNoteButton note={mockNote} />);

    // Click the export button
    const exportBtn = screen.getByRole("button", { name: /export/i });
    fireEvent.click(exportBtn);

    // 1. Verify Blob Content
    expect(BlobSpy).toHaveBeenCalled();
    const mockCalls = BlobSpy.mock.calls[0];
    const blobContent = mockCalls?.[0]?.[0] as string;

    expect(blobContent).toContain(`<title>${mockNote.title}</title>`);
    expect(blobContent).toContain(`<h1>${mockNote.title}</h1>`);
    expect(blobContent).toContain(`Content: ${mockNote.content}`);
    expect(blobContent).toContain("Last updated:");
    expect(blobContent).toContain("Generated by 10pShine Notes");

    // 2. Verify Download Mechanism
    expect(globalThis.URL.createObjectURL).toHaveBeenCalled();

    // Check if the mock anchor was configured correctly
    const anchor = document.createElement("a");
    expect(anchor.href).toBe("blob:mock-url-123");
    expect(anchor.download).toBe("Project_Alpha.html");

    // Verify click was called
    expect(anchor.click).toHaveBeenCalled();

    // 3. Verify Cleanup
    expect(globalThis.URL.revokeObjectURL).toHaveBeenCalledWith(
      "blob:mock-url-123",
    );
  });
});
